### ISSUE TITLE
homebrew deprecated message

### ISSUE THREAD

**Issue by CaledoniaProject** [ericchiang/pup#72]
I'm getting a deprecated message

```.%> brew install https://raw.githubusercontent.com/EricChiang/pup/master/pup.rb
######################################################################## 100.0%
Warning: Calling Hardware.is_64_bit? is deprecated!
Use Hardware::CPU.is_64_bit? instead.
/.../homebrew/Formula/pup.rb:7:in `<class:Pup>'

Warning: Calling Hardware.is_64_bit? is deprecated!
Use Hardware::CPU.is_64_bit? instead.
/../homebrew/Formula/pup.rb:7:in `<class:Pup>'
```

Can you update?

**Comment by chrisopedia** [comment]
@ericchiang can you close this issue?
