### ISSUE TITLE
fatal error parsing large file

### ISSUE THREAD

**Issue by heisters** [ericchiang/pup#76]
```
→ pup --version
0.4.0
```

I am frequently getting the following error trying to parse large HTML files (this one is 71M):

```
→ cat data.txt | pup '.entry-content p'
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x1d83b]

runtime stack:
runtime.throw(0x246e20, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x3ca600)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x3ca600, 0x1, 0x15, 0x9b0590)
	/usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc820043e58)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x3ca600, 0x1, 0x10000000015, 0x1d4df)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x3cc200, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x3cc200, 0x9b0590)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x42f000, 0xc800000015, 0x9b0590)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc820020000)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc82049d8c0 sp=0xc82049d8b8
runtime.mallocgc(0x180, 0x1caa60, 0x0, 0xc8277ef1f8)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc82049d998 sp=0xc82049d8c0
runtime.newarray(0x1caa60, 0x8, 0xc8277ef1f8)
	/usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc82049d9d8 sp=0xc82049d998
runtime.growslice(0x16b5a0, 0xc825afb140, 0x4, 0x4, 0x5, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:100 +0x2c1 fp=0xc82049da48 sp=0xc82049d9d8
github.com/ericchiang/pup/vendor/golang.org/x/net/html.(*Tokenizer).Token(0xc820063380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/ericchiang/pup/vendor/golang.org/x/net/html/token.go:1176 +0x4b1 fp=0xc82049db68 sp=0xc82049da48
github.com/ericchiang/pup/vendor/golang.org/x/net/html.(*parser).parse(0xc8200b1ad0, 0x0, 0x0)
	/go/src/github.com/ericchiang/pup/vendor/golang.org/x/net/html/parse.go:2002 +0xe6 fp=0xc82049dc10 sp=0xc82049db68
github.com/ericchiang/pup/vendor/golang.org/x/net/html.Parse(0x4837d0, 0xc8200ee000, 0x0, 0x0, 0x0)
	/go/src/github.com/ericchiang/pup/vendor/golang.org/x/net/html/parse.go:2026 +0x127 fp=0xc82049dc48 sp=0xc82049dc10
main.ParseHTML(0x4837d0, 0xc8200ee000, 0x0, 0x0, 0xc820034008, 0x0, 0x0)
	/go/src/github.com/ericchiang/pup/parse.go:43 +0xdf fp=0xc82049dd28 sp=0xc82049dc48
main.main()
	/go/src/github.com/ericchiang/pup/pup.go:30 +0x229 fp=0xc82049df50 sp=0xc82049dd28
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc82049dfa0 sp=0xc82049df50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82049dfa8 sp=0xc82049dfa0
```

While I don't know Go, it looks like a malloc error. This system has 6GB of free memory out of 16GB.

**Comment by ericchiang** [comment]
@heisters do you have the ability to install a newer version of go (I think the current builder uses 1.6.3) and see if the problem persists? E.g. install go and run

```
go get -u github.com/ericchiang/pup
$( go env GOPATH )/bin/pup < (filename)
```

**Comment by heisters** [comment]
Sorry, go was installed just for pup by homebrew. After trying to get this to work, I moved on to doing it with nokogiri, and uninstalled pup and its dependencies.

**Comment by ericchiang** [comment]
Okay thanks for the report. Going to close out this issue then.
