### ISSUE TITLE
Intermittent fatal happening on MacOS 10.12.6.

### ISSUE THREAD

**Issue by mmmmmrob** [ericchiang/pup#89]
Intermittent fatal happening on MacOS 10.12.6.

Same files and selectors fail intermittently with this fault:

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x1d83b]

runtime stack:
runtime.throw(0x246e20, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x3ca600)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x3ca600, 0x1, 0x5, 0x434c98)
	/usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbff8f8)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x3ca600, 0x1, 0x10000000005, 0x1d4df)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x3cbb00, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x3cbb00, 0xc8200186f8)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x42f4b0, 0x5, 0xc820033cf8)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x3c7200)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc820033c88 sp=0xc820033c80
runtime.mallocgc(0x40, 0x1cce60, 0x1, 0x3)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc820033d60 sp=0xc820033c88
runtime.newarray(0x1cce60, 0x1, 0x47b6a5baee7662f1)
	/usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc820033da0 sp=0xc820033d60
runtime.mapassign1(0x178180, 0xc82008a270, 0x26e840, 0x26e844)
	/usr/local/go/src/runtime/hashmap.go:453 +0x134 fp=0xc820033e48 sp=0xc820033da0
github.com/ericchiang/pup/vendor/golang.org/x/text/language.init()
	/go/src/github.com/ericchiang/pup/vendor/golang.org/x/text/language/index.go:759 +0x14d fp=0xc820033ea8 sp=0xc820033e48
github.com/ericchiang/pup/vendor/golang.org/x/text/encoding/htmlindex.init()
	/go/src/github.com/ericchiang/pup/vendor/golang.org/x/text/encoding/htmlindex/tables.go:352 +0x56 fp=0xc820033ee0 sp=0xc820033ea8
github.com/ericchiang/pup/vendor/golang.org/x/net/html/charset.init()
	/go/src/github.com/ericchiang/pup/vendor/golang.org/x/net/html/charset/charset.go:257 +0x63 fp=0xc820033ee8 sp=0xc820033ee0
main.init()
	/go/src/github.com/ericchiang/pup/selector.go:638 +0x79 fp=0xc820033f50 sp=0xc820033ee8
runtime.main()
	/usr/local/go/src/runtime/proc.go:177 +0x27f fp=0xc820033fa0 sp=0xc820033f50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820033fa8 sp=0xc820033fa0
```

**Comment by mmmmmrob** [comment]
Looks like this was fixed by a `brew update && brew reinstall pup`
